### ISSUE TITLE
微站网页版url路径规范

### ISSUE THREAD

**Issue by steedos** [steedos/mini-vip#334]
- 配置域名 *.hotoa.com，指向外网vip服务。
- 每个工作区开通之后，域名 {space_id}.hotoa.com 自动指向该工作区的网站。
- 未来允许工作区管理员绑定自定义域名。

网站的访问地址为：
- 主页 http://{space_id}.hotoa.com/
- 文章 http://{space_id}.hotoa.com/post/{post_id}
- 栏目 http://{space_id}.hotoa.com/tag/{tag_id}

在文章中可以输入以上格式的网址链接，小程序中自动识别并转换为页面跳转。

**Comment by yinlianghui** [comment]
其他已实现，tag功能未实现
