### ISSUE TITLE
根据新的分享规则增加了vip_customers表，之前的会员卡/members相关逻辑需要关联到这张新表

### ISSUE THREAD

**Issue by yinlianghui** [steedos/mini-vip#351]
- vip_customers表相当于客户的space_users，以前是记录在space_users中，要迁移到这个新表
- 之前的会员卡/members相关逻辑是关联到space_users表，也要重新关联到新表

**Comment by liminglang** [comment]
- vip_customers什么时候新增记录？第一次进入该商户的任何界面时。激活会员卡后要更新此记录
- space_users没有member的概念了，每个model下针对member给的权限也可以删除了。
- 员工和admin修改了个人信息，要同步至space_users；会员修改了个人信息，要同步至vip_customers
