### ISSUE TITLE
LOVE平台算法逻辑处理

### ISSUE THREAD

**Issue by yinlianghui** [steedos/mini-vip#396]

**Comment by sunhaolin** [comment]
整理完整算法 wiki

**Comment by sunhaolin** [comment]
- 涉及的数据加载到内存
- 根据硬性条件（性别，年龄，身高）过滤数据
- 根据答题表，计算love_result
-  根据love_result数据计算 一对一匹配结果 love_recommend (同时将现有的love_recommend数据维护至love_recommend_histroy)
-
