### ISSUE TITLE
会员卡功能

### ISSUE THREAD

**Issue by zonglu233** [steedos/mini-vip#411]
如果非会员，点击我的头像
- 输入邀请码，如果正确，自动激活会员卡
- 跳过邀请码，进入会员卡开卡界面，并付费200

如果已经是会员，进入会员卡主界面

**Comment by baozhoutao** [comment]
刚开始就输入了邀请码
刚开始在邀请码界面点击了跳过(需微调程序)

**Comment by baozhoutao** [comment]
_创建邀请码时，必须选择对应的“卡项”_
