### ISSUE TITLE
摇一摇匹配不到用户时，随机提示语。

### ISSUE THREAD

**Issue by lizhenghotoa** [steedos/mini-vip#434]

**Comment by zhusijia** [comment]
- 没摇到上方提示"千万人之中，两个人相遇的概率是0.00053，本周有缘人已与你擦肩而过，请期待下周的匹配。"

- 下方tips:
   1.你与有缘人的距离，也许只隔了一个共同好友，让更多的朋友加入“无颜”吧
   2.你习惯向左走，我习惯向右走，却始终不曾相遇。邀请更多好友匹配，也许缘分就在你的身边。
   3.我们生活在同一个城市，但从不认识彼此。邀请更多朋友加入“无颜”交友吧。
