### ISSUE TITLE
商城：订单详情页的改进

### ISSUE THREAD

**Issue by marchtian** [steedos/mini-vip#487]
- [x] （1）如果订单已取消，建议增加显示 取消时间
- [x] （2）如果订单已完成（支付），建议增加显示 支付时间
- [x] （3）收货地址显示有问题，如果下单后 修改了地址，则显示为 修改后的
- [x] （4）即便已取消，仍然显示：“支付方式：微信；实付：￥1”
- [ ] （5）除了 实付多少钱，建议增加 优惠多少钱（商家在后台改的）

**Comment by baozhoutao** [comment]
第三个问题经过测试，未能重现

**Comment by baozhoutao** [comment]
问题5拆分到独立的任务：https://github.com/steedos/mini-vip/issues/574
