### ISSUE TITLE
vip_groups表未记录space_id值

### ISSUE THREAD

**Issue by yinlianghui** [steedos/mini-vip#571]
下次CN的creator上线前：
- 请孙老师帮忙执行个脚本把这个表在CN上的所有记录都加上space值，指向我们的love平台space_id
- 建议creator上线后再执行一次脚本
- 新版本的小程序要等cn的creator先上线再发包

**Comment by sunhaolin** [comment]
`db.getCollection('vip_groups').update({}, {$set: {space: 'Lnre96ro35Wf9b3gA'}}, {multi: true})`
