### ISSUE TITLE
点击榜单一行，查看详情

### ISSUE THREAD

**Issue by liminglang** [steedos/mini-vip#605]
1.总结出来的标题（情敌指数超过90%，我喜欢她的指数超过90%，她喜欢我的指数超过90%，其他情况）
2.我的头像   （根据匹配关系而来的小图标：❤，心碎，火，family等，分别表示匹配度大于60%且符合筛选添加，不符合筛选条件或匹配度小于60%，情敌，符合筛选条件且匹配度大于60%小于90%）   对方的头像（对方对象下有一行显示对方昵称和一个向右的箭头，点击向右的箭头查看对方的交友名片）
3.根据双方的匹配度，匹配总结（内容是从各个角度计算的指数，比如：性格匹配指数，情敌指数，她是否满足我的筛选条件，我是否满足她的筛选条件）
4.右下角给出无颜小程序的二维码(扫描此二维码进入无颜首页)
5.按钮：分享到群（从群里点开链接，进入此页面），我也要玩（进入index页面）

**Comment by steedos** [comment]
https://github.com/steedos/mini-vip/issues/603

**Comment by liminglang** [comment]
榜单分为三种（喜欢我的（主题目：我的性格特征），我喜欢的（副题目：我喜欢的类型），以及总匹配度）。
同性：
 - [ ] 榜单“我喜欢的”匹配度大于“喜欢我的”，且二人的筛选条件重合；则判定为情敌。若筛选条件不重合，则判定为兄弟/姐妹
 - [ ] 榜单“喜欢我的”匹配度大于“我喜欢的”，则判定为同一类型的人，标题是：“we are family”
 
异性：
- [ ] 总的匹配度大于80%，且互相满足双方的筛选条件。判定为天生一对。Ta可能就是你要找的白马王子/白雪公主。
