### ISSUE TITLE
交友名片主入口

### ISSUE THREAD

**Issue by steedos** [steedos/mini-vip#669]
用户可以生成自己的交友二维码
- 发论坛
- 发朋友圈
- 转发到群

陌生人二维码扫描进入交友名片
- 应该比较详细的列出主要的用户信息
- 匹配度显示为问号，点击进入天生一对界面，引导用户开始测试。
- 测试完成，回到天生一对界面，显示测试结果
  - 我也要玩，生成我的二维码
  - 想要找到匹配度更高的人？进入每周推荐页面

**Comment by marchtian** [comment]
现有“交友名片”的修改
1.个人情况 与 “符合不符合筛选条件”之间增加一行，显示我和他的匹配度，如果我没有注册或没有答完题目，显示为“？”，并可以 点击进入“天生一对”页面
2. 如果我没有注册或没有答完题目（即匹配度为？时），不显示 “符合不符合筛选条件”
3. 4行卷子（缘分卷等）放开显示，考虑只显示其中答过的
4. 本页面的 美化 待1-3出来后讨论优化
