### ISSUE TITLE
home页改造

### ISSUE THREAD

**Issue by steedos** [steedos/mini-vip#671]
- index 页面如果用户未答完三套题，进入引导页面，引导用户答题
- index 页面如果用户已经答完三套题，进入home页。不需要返回按钮。
- 主页面
  - 头部区域，现在头部太大，头像部分简化成 “我“的风格。头像点击，进入我的交友名片，可以预览和编辑交友名片
  - 每周推荐，（如果服务端没开开关，则隐藏）
  - 我的缘分榜

**Comment by yinlianghui** [comment]
交友名片功能在独立的issue中：能在资料详情页查看到这个人的所有信息，比如兴趣爱好，工作经历，教育经历。 #668
