### ISSUE TITLE
无颜服务端调整

### ISSUE THREAD

**Issue by sunhaolin** [steedos/mini-vip#714]
###无颜服务端调整：
- user表增加基本信息字段（新增的字段及从love_about_me来的字段，love_about_me修改时需要自动更新users）
- odata接口针对user表做特殊处理（权限判断，字段查询修改限制，不能删除新增）

**Comment by yinlianghui** [comment]
已实现ODATA中允许所有用户查看用户信息并且能编辑自己的用户信息
未实现功能：
- 字段中增加odata属性功能，为false表示不支持odata查询修改
- users表的modal中odata的false属性配置在哪些字段中，以禁用这些字段的odata权限
- users表中modal中字段顺序应该改为跟EC名片一样

**Comment by sunhaolin** [comment]
现状已满足此需求，无需增加odata属性
