### ISSUE TITLE
名片小程序老数据同步问题

### ISSUE THREAD

**Issue by yinlianghui** [steedos/mini-vip#744]
- 有mobile，没有mobile2，所以下面（图1）的效果中手机是空的，需要写脚本把mobile值同步到mobile2及wechat字段中。
- 老用户已经登录过了，所以不会要再次登录，这样之前的头像数据就没有同步到avatarUrl中，所以下面（图2）中看到老用户头像是空的。
![image](https://user-images.githubusercontent.com/6219465/46661480-dcfb2600-cbeb-11e8-8a5f-5fcc4ed068e7.png)
![image](https://user-images.githubusercontent.com/6219465/46661551-02882f80-cbec-11e8-95cd-647e9190f06e.png)

**Comment by sunhaolin** [comment]
```js
db.getCollection('users').find({
    mobile: {
        $exists: true
    },
    mobile2: {
        $exists: false
    }
}).forEach(function (u) {
    db.getCollection('users').update({
        _id: u._id
    }, {
        $set: {
            mobile2: u.mobile,
            wechat: u.mobile
        }
    })
})
```
